import {
  LayoutDashboard, Package, FileText, Map, Megaphone,
  Briefcase, Image, Users, Settings, ScrollText,
  ToggleLeft, History, BookOpen, HelpCircle, Menu,
  Home, Shield, Key, Fingerprint, Bell, UserCog,
  Tags, Globe, Activity, Server, Code, Terminal,
  Box, HardDrive, Mail, Search, Cpu, Database,
  AlertTriangle, BarChart3, GitBranch, LifeBuoy, Wrench, FileSearch, Monitor, Camera,
  Layers, Clock, FolderOpen, FileSpreadsheet, Thermometer,
  Rocket, Zap, Lock, HeartPulse, FlaskConical, BookText, ShieldCheck,
  CheckCircle,
} from 'lucide-react'
import type { NavGroup } from '@/lib/platform/registries/NavigationRegistry'

export const coreNavGroups: NavGroup[] = [
  {
    id: 'overview',
    labelEn: 'Overview',
    labelAr: 'نظرة عامة',
    moduleId: 'core',
    order: 0,
    items: [
      { href: '/admin/dashboard', labelEn: 'Dashboard', labelAr: 'لوحة التحكم', icon: LayoutDashboard, moduleId: 'core' },
    ],
  },
  {
    id: 'content',
    labelEn: 'Content',
    labelAr: 'المحتوى',
    moduleId: 'core',
    order: 1,
    items: [
      { href: '/admin/products',     labelEn: 'Products',     labelAr: 'المنتجات',     icon: Package,    permission: 'manage_products',   moduleId: 'core' },
      { href: '/admin/docs',         labelEn: 'Documentation',labelAr: 'التوثيق',      icon: FileText,   permission: 'manage_docs',      moduleId: 'core' },
      { href: '/admin/static-pages', labelEn: 'Static Pages', labelAr: 'الصفحات الثابتة', icon: BookOpen, permission: 'manage_static_pages', moduleId: 'core' },
      { href: '/admin/faq',          labelEn: 'FAQ',          labelAr: 'الأسئلة الشائعة', icon: HelpCircle, permission: 'manage_faqs',    moduleId: 'core' },
      { href: '/admin/menus',        labelEn: 'Menus',        labelAr: 'القوائم',        icon: Menu,       permission: 'manage_menus',     moduleId: 'core' },
      { href: '/admin/homepage',     labelEn: 'Homepage',     labelAr: 'الصفحة الرئيسية', icon: Home,       permission: 'manage_homepage',  moduleId: 'core' },
      { href: '/admin/releases',     labelEn: 'Releases',     labelAr: 'الإصدارات',     icon: Tags,       permission: 'manage_releases',  moduleId: 'core' },
      { href: '/admin/roadmap',      labelEn: 'Roadmap',      labelAr: 'خارطة الطريق',  icon: Map,        permission: 'manage_roadmap',   moduleId: 'core' },
      { href: '/admin/updates',      labelEn: 'Updates',      labelAr: 'المستجدات',     icon: Megaphone,  permission: 'manage_updates',   moduleId: 'core' },
      { href: '/admin/careers',      labelEn: 'Careers',      labelAr: 'الوظائف',       icon: Briefcase,  permission: 'manage_careers',   moduleId: 'core' },
      { href: '/admin/timeline',     labelEn: 'Timeline',     labelAr: 'الجدول الزمني',  icon: History,    permission: 'manage_timeline',  moduleId: 'core' },
    ],
  },
  {
    id: 'media',
    labelEn: 'Media',
    labelAr: 'الوسائط',
    moduleId: 'core',
    order: 2,
    items: [
      { href: '/admin/media', labelEn: 'Media Library', labelAr: 'مكتبة الوسائط', icon: Image, permission: 'manage_media', moduleId: 'core' },
    ],
  },
  {
    id: 'system',
    labelEn: 'System',
    labelAr: 'النظام',
    moduleId: 'core',
    order: 3,
    items: [
      { href: '/admin/users',         labelEn: 'Users',          labelAr: 'المستخدمون',       icon: Users,       permission: 'manage_users', moduleId: 'core' },
      { href: '/admin/roles',         labelEn: 'Roles & Permissions', labelAr: 'الأدوار والصلاحيات', icon: UserCog, permission: 'manage_roles', moduleId: 'core' },
      { href: '/admin/settings',      labelEn: 'Settings',       labelAr: 'الإعدادات',        icon: Settings,    moduleId: 'core' },
      { href: '/admin/feature-flags', labelEn: 'Feature Flags',  labelAr: 'مفاتيح الميزات',    icon: ToggleLeft, permission: 'manage_feature_flags', moduleId: 'core' },
    ],
  },
  {
    id: 'security',
    labelEn: 'Security',
    labelAr: 'الأمان',
    moduleId: 'core',
    order: 4,
    items: [
      { href: '/admin/audit-logs',    labelEn: 'Audit Logs',    labelAr: 'سجلات التدقيق',  icon: ScrollText, permission: 'view_audit_logs', moduleId: 'core' },
      { href: '/admin/sessions',      labelEn: 'Active Sessions',labelAr: 'الجلسات النشطة', icon: Fingerprint, moduleId: 'core' },
      { href: '/admin/login-history', labelEn: 'Login History',  labelAr: 'سجل الدخول',     icon: Shield,     moduleId: 'core' },
      { href: '/admin/api-tokens',    labelEn: 'API Tokens',     labelAr: 'رموز API',       icon: Key,        moduleId: 'core' },
    ],
  },
  {
    id: 'notifications',
    labelEn: 'Notifications',
    labelAr: 'الإشعارات',
    moduleId: 'core',
    order: 5,
    items: [
      { href: '/admin/notifications', labelEn: 'Notification Center', labelAr: 'مركز الإشعارات', icon: Bell, moduleId: 'core' },
    ],
  },
  {
    id: 'platform',
    labelEn: 'Platform',
    labelAr: 'المنصة',
    moduleId: 'core',
    order: 6,
    items: [
      { href: '/admin/platform/overview',  labelEn: 'Platform Overview',  labelAr: 'نظرة عامة على المنصة',  icon: Activity,  moduleId: 'core' },
      { href: '/admin/platform/modules',   labelEn: 'Module Manager',     labelAr: 'مدير الوحدات',        icon: Package,   moduleId: 'core' },
      { href: '/admin/platform/registries',labelEn: 'Registry Inspector', labelAr: 'مفتش السجلات',        icon: Globe,     moduleId: 'core' },
      { href: '/admin/platform/health',    labelEn: 'System Health',      labelAr: 'صحة النظام',          icon: Activity,  moduleId: 'core' },
      { href: '/admin/platform/events',    labelEn: 'Event Center',       labelAr: 'مركز الأحداث',       icon: Activity,  moduleId: 'core' },
      { href: '/admin/platform/versions',  labelEn: 'Version Center',     labelAr: 'مركز الإصدارات',     icon: Tags,      moduleId: 'core' },
      { href: '/admin/platform/developer', labelEn: 'Developer Center',   labelAr: 'مركز المطورين',      icon: Code,      moduleId: 'core' },
      { href: '/admin/platform/drivers',   labelEn: 'Drivers',            labelAr: 'المشغلات',           icon: Server,    moduleId: 'core' },
      { href: '/admin/platform/commands',  labelEn: 'Command Bus',        labelAr: 'حافلة الأوامر',      icon: Terminal,  moduleId: 'core' },
      { href: '/admin/platform/queries',   labelEn: 'Query Bus',          labelAr: 'حافلة الاستعلامات',  icon: Database,  moduleId: 'core' },
      { href: '/admin/platform/pipeline',  labelEn: 'Pipeline',           labelAr: 'خط الأنابيب',        icon: Cpu,       moduleId: 'core' },
      { href: '/admin/platform/sdk',       labelEn: 'Product SDK',        labelAr: 'SDK المنتج',         icon: Box,       moduleId: 'core' },
      { href: '/admin/platform/generator', labelEn: 'Module Generator',   labelAr: 'مولد الوحدات',       icon: Code,      moduleId: 'core' },
      { href: '/admin/platform/cache',     labelEn: 'Cache',              labelAr: 'الذاكرة المؤقتة',     icon: HardDrive, moduleId: 'core' },
      { href: '/admin/platform/storage',   labelEn: 'Storage',            labelAr: 'التخزين',            icon: Server,    moduleId: 'core' },
      { href: '/admin/platform/mail',      labelEn: 'Mail',               labelAr: 'البريد',             icon: Mail,      moduleId: 'core' },
      { href: '/admin/platform/search',    labelEn: 'Search',             labelAr: 'البحث',              icon: Search,    moduleId: 'core' },
      { href: '/admin/platform/manifest',  labelEn: 'Platform Manifest',   labelAr: 'بيان المنصة',        icon: FileText,  moduleId: 'core' },
      { href: '/admin/platform/runtime',   labelEn: 'Runtime Inspector',   labelAr: 'مفتش التشغيل',       icon: Monitor,   moduleId: 'core' },
      { href: '/admin/platform/snapshot',  labelEn: 'Platform Snapshot',   labelAr: 'لقطة المنصة',        icon: Camera,    moduleId: 'core' },
      { href: '/admin/platform/visualizer',labelEn: 'Dependency Visualizer',labelAr: 'تصور التبعيات',     icon: GitBranch, moduleId: 'core' },
      { href: '/admin/platform/compatibility',labelEn: 'Compatibility',    labelAr: 'التوافق',            icon: Wrench,    moduleId: 'core' },
      { href: '/admin/platform/lifecycle', labelEn: 'Lifecycle Monitor',   labelAr: 'مراقب دورة الحياة',  icon: LifeBuoy,  moduleId: 'core' },
      { href: '/admin/platform/errors',    labelEn: 'Error Catalog',       labelAr: 'كتالوج الأخطاء',     icon: AlertTriangle, moduleId: 'core' },
      { href: '/admin/platform/reports',   labelEn: 'Platform Reports',    labelAr: 'تقارير المنصة',       icon: BarChart3, moduleId: 'core' },
      { href: '/admin/platform/configuration',labelEn: 'Configuration',    labelAr: 'الإعدادات',          icon: Settings,  moduleId: 'core' },
      { href: '/admin/platform/diagnostics',labelEn: 'Diagnostics',        labelAr: 'التشخيص',            icon: FileSearch,moduleId: 'core' },
      { href: '/admin/platform/audit',     labelEn: 'Platform Audit',      labelAr: 'تدقيق المنصة',       icon: Shield,    moduleId: 'core' },
      { href: '/admin/platform/queues',    labelEn: 'Queue Manager',       labelAr: 'مدير قوائم الانتظار', icon: Layers,  moduleId: 'core' },
      { href: '/admin/platform/workers',   labelEn: 'Worker Manager',      labelAr: 'مدير العمال',        icon: Server,    moduleId: 'core' },
      { href: '/admin/platform/scheduler', labelEn: 'Scheduler',           labelAr: 'المجدول',            icon: Clock,     moduleId: 'core' },
      { href: '/admin/platform/media',     labelEn: 'Media Center',        labelAr: 'مركز الوسائط',       icon: FolderOpen, moduleId: 'core' },
      { href: '/admin/platform/logs',      labelEn: 'Log Center',          labelAr: 'مركز السجلات',       icon: FileSpreadsheet, moduleId: 'core' },
      { href: '/admin/platform/monitoring',labelEn: 'Monitoring',          labelAr: 'المراقبة',           icon: Thermometer, moduleId: 'core' },
      { href: '/admin/platform/deployments',labelEn: 'Deployments',        labelAr: 'النشر',              icon: Rocket,   moduleId: 'core' },
      { href: '/admin/platform/performance',labelEn: 'Performance',        labelAr: 'الأداء',             icon: Zap,      moduleId: 'core' },
      { href: '/admin/platform/releases', labelEn: 'Releases',         labelAr: 'الإصدارات',        icon: Tags,      moduleId: 'core' },
      { href: '/admin/platform/recovery',  labelEn: 'Disaster Recovery',labelAr: 'التعافي من الكوارث', icon: HeartPulse, moduleId: 'core' },
      { href: '/admin/platform/environment',labelEn: 'Environment',     labelAr: 'البيئة',            icon: FlaskConical, moduleId: 'core' },
      { href: '/admin/platform/health-endpoints',labelEn: 'Health Endpoints',labelAr: 'نقاط الصحة',   icon: Activity,  moduleId: 'core' },
      { href: '/admin/platform/documentation',labelEn: 'Documentation',    labelAr: 'الوثائق',        icon: BookText,  moduleId: 'core' },
      { href: '/admin/platform/installation', labelEn: 'Installation',     labelAr: 'التثبيت',         icon: Wrench,    moduleId: 'core' },
    ],
  },
]
